# Site settings
title: Mon Blog sur Jekyll
email: jmarck4@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "Hello guy's! Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jmarck4.github.io" # the base hostname & protocol for your site
twitter_username: BlogOnWordPress
github_username:  jmarck4

# Build settings
markdown: kramdown

